### ISSUE TITLE
Incompatible with PHP 8+

### ISSUE THREAD

**Issue by GamesmenJordan** [Space48/magedbm2#66]
It should be noted that this tool doesn't work with PHP 8. Attempting to run with PHP 8 returns an error.

```
PHP Fatal error:  Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php:738
Stack trace:
#0 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(738): abs()
#1 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(387): Symfony\Component\Yaml\Parser->parseValue()
#2 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(515): Symfony\Component\Yaml\Parser->doParse()
#3 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(240): Symfony\Component\Yaml\Parser->parseBlock()
#4 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(515): Symfony\Component\Yaml\Parser->doParse()
#5 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(365): Symfony\Component\Yaml\Parser->parseBlock()
#6 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(141): Symfony\Component\Yaml\Parser->doParse()
#7 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php(77): Symfony\Component\Yaml\Parser->parse()
#8 phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Yaml.php(62): Symfony\Component\Yaml\Parser->parseFile()
#9 phar:///usr/local/bin/magedbm2/src/Application/ConfigLoader/FileLoader.php(34): Symfony\Component\Yaml\Yaml::parseFile()
#10 phar:///usr/local/bin/magedbm2/etc/di.php(83): Meanbee\Magedbm2\Application\ConfigLoader\FileLoader->asConfig()
#11 [internal function]: DI\Definition\Source\DefinitionFile->{closure}()
#12 phar:///usr/local/bin/magedbm2/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()
#13 phar:///usr/local/bin/magedbm2/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#14 phar:///usr/local/bin/magedbm2/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve()
#15 phar:///usr/local/bin/magedbm2/vendor/php-di/php-di/src/Container.php(377): DI\Definition\Resolver\ResolverDispatcher->resolve()
#16 phar:///usr/local/bin/magedbm2/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition()
#17 phar:///usr/local/bin/magedbm2/src/Application.php(101): DI\Container->get()
#18 phar:///usr/local/bin/magedbm2/vendor/symfony/console/Application.php(148): Meanbee\Magedbm2\Application->doRun()
#19 phar:///usr/local/bin/magedbm2/bin/magedbm2(10): Symfony\Component\Console\Application->run()
#20 /usr/local/bin/magedbm2(10): require('...')
#21 {main}
  thrown in phar:///usr/local/bin/magedbm2/vendor/symfony/yaml/Parser.php on line 738
```

Whilst this can be inferred by PHP 7.0+, it is worth noting this point explicitly and I am opening this issue to make it obvious for others who might encounter this error and be confused as to why.

**Comment by vlad1992** [comment]
tackled in release 4.0.0
